"""legacy schema baseline

Revision ID: 20260710_0000
Revises:
Create Date: 2026-07-12 00:27:17.147142
"""
from alembic import op
import sqlalchemy as sa


revision = "20260710_0000"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_rate_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('janela_inicio', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'endpoint', name='uq_ip_endpoint')
    )
    op.create_index(op.f('ix_api_rate_limits_endpoint'), 'api_rate_limits', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_rate_limits_ip'), 'api_rate_limits', ['ip'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('numero_casa', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cnpj'), 'clientes', ['cnpj'], unique=False)
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('dias_vencimento', sa.Integer(), nullable=True),
    sa.Column('dados_pagamento', sa.Text(), nullable=True),
    sa.Column('pix_chave', sa.String(length=200), nullable=True),
    sa.Column('meta_receita_mensal', sa.Float(), nullable=True),
    sa.Column('alerta_caixa_minimo', sa.Float(), nullable=True),
    sa.Column('alerta_estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('alerta_vencimento_dias', sa.Integer(), nullable=True),
    sa.Column('wkhtmltopdf_path', sa.String(length=500), nullable=True),
    sa.Column('wpp_server_url', sa.String(length=300), nullable=True),
    sa.Column('evolution_api_url', sa.String(length=600), nullable=True),
    sa.Column('evolution_api_key', sa.String(length=600), nullable=True),
    sa.Column('evolution_instance', sa.String(length=100), nullable=True),
    sa.Column('dashboard_widgets', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defeitos_padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_aparelho', sa.String(length=100), nullable=True),
    sa.Column('sintoma', sa.String(length=300), nullable=False),
    sa.Column('causa', sa.Text(), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=False)
    op.create_index(op.f('ix_fornecedores_email'), 'fornecedores', ['email'], unique=False)
    op.create_table('login_attempts',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('falhas', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(), nullable=True),
    sa.Column('ultima_falha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eventos_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('operacao', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_aparelho', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('defeito_alegado', sa.Text(), nullable=True),
    sa.Column('defeito_encontrado', sa.Text(), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('valor_servico', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_pecas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prio', sa.String(length=20), nullable=True),
    sa.Column('tecnico_nome', sa.String(length=120), nullable=True),
    sa.Column('garantia_dias', sa.Integer(), nullable=True),
    sa.Column('data_prev', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('margem', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coletas_agendadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('numero_casa', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coletas_agendadas_cliente_id'), 'coletas_agendadas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_data_agendada'), 'coletas_agendadas', ['data_agendada'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_os_id'), 'coletas_agendadas', ['os_id'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_status'), 'coletas_agendadas', ['status'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_usuario_id'), 'coletas_agendadas', ['usuario_id'], unique=False)
    op.create_table('os_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('os_pecas',
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('os_id', 'peca_id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('os_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('coleta_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coleta_id'], ['coletas_agendadas.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_fotos_coleta_id'), 'os_fotos', ['coleta_id'], unique=False)
    op.create_index(op.f('ix_os_fotos_os_id'), 'os_fotos', ['os_id'], unique=False)
    op.create_index(op.f('ix_os_fotos_usuario_id'), 'os_fotos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_os_fotos_usuario_id'), table_name='os_fotos')
    op.drop_index(op.f('ix_os_fotos_os_id'), table_name='os_fotos')
    op.drop_index(op.f('ix_os_fotos_coleta_id'), table_name='os_fotos')
    op.drop_table('os_fotos')
    op.drop_table('transacoes')
    op.drop_table('os_pecas')
    op.drop_table('os_historico')
    op.drop_index(op.f('ix_coletas_agendadas_usuario_id'), table_name='coletas_agendadas')
    op.drop_index(op.f('ix_coletas_agendadas_status'), table_name='coletas_agendadas')
    op.drop_index(op.f('ix_coletas_agendadas_os_id'), table_name='coletas_agendadas')
    op.drop_index(op.f('ix_coletas_agendadas_data_agendada'), table_name='coletas_agendadas')
    op.drop_index(op.f('ix_coletas_agendadas_cliente_id'), table_name='coletas_agendadas')
    op.drop_table('coletas_agendadas')
    op.drop_table('pecas')
    op.drop_table('ordens_servico')
    op.drop_table('eventos_log')
    op.drop_table('usuarios')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_fornecedores_email'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_table('defeitos_padrao')
    op.drop_table('configuracoes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_api_rate_limits_ip'), table_name='api_rate_limits')
    op.drop_index(op.f('ix_api_rate_limits_endpoint'), table_name='api_rate_limits')
    op.drop_table('api_rate_limits')
    # ### end Alembic commands ###
