"""initial mysql schema

Revision ID: 20260718_0001
Revises:
Create Date: 2026-07-18 18:34:28.010604
"""
import sqlalchemy as sa
from alembic import op

revision = '20260718_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_rate_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('janela_inicio', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'endpoint', name='uq_ip_endpoint')
    )
    op.create_index(op.f('ix_api_rate_limits_endpoint'), 'api_rate_limits', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_rate_limits_ip'), 'api_rate_limits', ['ip'], unique=False)
    op.create_table('laudo_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('proximo_numero', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'ano', name='uq_laudo_counter_org_ano')
    )
    op.create_table('login_attempts',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('falhas', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(), nullable=True),
    sa.Column('ultima_falha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('operational_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_alerts_fingerprint'), 'operational_alerts', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_operational_alerts_severity'), 'operational_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_operational_alerts_source'), 'operational_alerts', ['source'], unique=False)
    op.create_table('operational_heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('last_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_duration_ms', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_uuid', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_uuid'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('limites', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_event_id', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_event_id', name='uq_billing_provider_event')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('numero_casa', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cnpj'), 'clientes', ['cnpj'], unique=False)
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_index(op.f('ix_clientes_organization_id'), 'clientes', ['organization_id'], unique=False)
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('subtitulo_empresa', sa.String(length=160), nullable=True),
    sa.Column('logo_url', sa.String(length=600), nullable=True),
    sa.Column('site_url', sa.String(length=300), nullable=True),
    sa.Column('instagram_url', sa.String(length=300), nullable=True),
    sa.Column('whatsapp_publico', sa.String(length=20), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('dias_vencimento', sa.Integer(), nullable=True),
    sa.Column('dados_pagamento', sa.Text(), nullable=True),
    sa.Column('pix_chave', sa.String(length=200), nullable=True),
    sa.Column('meta_receita_mensal', sa.Float(), nullable=True),
    sa.Column('alerta_caixa_minimo', sa.Float(), nullable=True),
    sa.Column('alerta_estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('alerta_vencimento_dias', sa.Integer(), nullable=True),
    sa.Column('dashboard_widgets', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('defeitos_padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('tipo_aparelho', sa.String(length=100), nullable=True),
    sa.Column('sintoma', sa.String(length=300), nullable=False),
    sa.Column('causa', sa.Text(), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defeitos_padrao_organization_id'), 'defeitos_padrao', ['organization_id'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=False)
    op.create_index(op.f('ix_fornecedores_email'), 'fornecedores', ['email'], unique=False)
    op.create_index(op.f('ix_fornecedores_organization_id'), 'fornecedores', ['organization_id'], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'event_type', 'channel', 'version', name='uq_message_template_version')
    )
    op.create_index(op.f('ix_message_templates_event_type'), 'message_templates', ['event_type'], unique=False)
    op.create_index(op.f('ix_message_templates_organization_id'), 'message_templates', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('recipient', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_notification_org_key')
    )
    op.create_index(op.f('ix_notifications_next_attempt_at'), 'notifications', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('organization_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('periodo_fim', sa.DateTime(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('service_checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'category', 'version', name='uq_checklist_org_category_version')
    )
    op.create_index(op.f('ix_service_checklist_templates_category'), 'service_checklist_templates', ['category'], unique=False)
    op.create_index(op.f('ix_service_checklist_templates_organization_id'), 'service_checklist_templates', ['organization_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('recovery_codes_hash', sa.JSON(), nullable=True),
    sa.Column('permissoes_extra', sa.JSON(), nullable=True),
    sa.Column('permissoes_negadas', sa.JSON(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('security_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_organization_id'), 'usuarios', ['organization_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=60), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_cliente_id'), 'consent_records', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_consent_records_organization_id'), 'consent_records', ['organization_id'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('solicitado_por_id', sa.Integer(), nullable=False),
    sa.Column('solicitado_em', sa.DateTime(), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_cliente_id'), 'data_subject_requests', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_organization_id'), 'data_subject_requests', ['organization_id'], unique=False)
    op.create_table('eventos_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('operacao', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_log_organization_id'), 'eventos_log', ['organization_id'], unique=False)
    op.create_table('laudo_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo_laudo', sa.String(length=30), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('declaracao_final', sa.Text(), nullable=True),
    sa.Column('rodape', sa.String(length=500), nullable=True),
    sa.Column('fotos_obrigatorias', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'nome', 'versao', name='uq_laudo_template_org_nome_versao')
    )
    op.create_index('ix_laudo_template_org_tipo_ativo', 'laudo_templates', ['organization_id', 'tipo_laudo', 'ativo'], unique=False)
    op.create_index(op.f('ix_laudo_templates_organization_id'), 'laudo_templates', ['organization_id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_aparelho', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('defeito_alegado', sa.Text(), nullable=True),
    sa.Column('defeito_encontrado', sa.Text(), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('valor_servico', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_pecas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orcamento_status', sa.String(length=20), nullable=True),
    sa.Column('orcamento_decidido_em', sa.DateTime(), nullable=True),
    sa.Column('checklist_template_id', sa.Integer(), nullable=True),
    sa.Column('checklist_snapshot', sa.JSON(), nullable=True),
    sa.Column('checklist_answers', sa.JSON(), nullable=True),
    sa.Column('authorization_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('authorization_accepted_by', sa.String(length=120), nullable=True),
    sa.Column('warranty_return_of_id', sa.Integer(), nullable=True),
    sa.Column('prio', sa.String(length=20), nullable=True),
    sa.Column('tecnico_nome', sa.String(length=120), nullable=True),
    sa.Column('garantia_dias', sa.Integer(), nullable=True),
    sa.Column('data_prev', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.Column('baixada_em', sa.DateTime(), nullable=True),
    sa.Column('baixada_por_id', sa.Integer(), nullable=True),
    sa.Column('baixa_observacao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['service_checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['baixada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['warranty_return_of_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ordens_servico_numero', 'ordens_servico', ['numero'], unique=False)
    op.create_index('ix_ordens_servico_baixada_em', 'ordens_servico', ['baixada_em'], unique=False)
    op.create_index(op.f('ix_ordens_servico_organization_id'), 'ordens_servico', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_warranty_return_of_id'), 'ordens_servico', ['warranty_return_of_id'], unique=False)
    op.create_index('uq_ordens_servico_org_numero', 'ordens_servico', ['organization_id', 'numero'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('solicitado_ip_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_password_reset_expires', 'password_reset_tokens', ['expira_em'], unique=False)
    op.create_index('ix_password_reset_user_created', 'password_reset_tokens', ['usuario_id', 'criado_em'], unique=False)
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('margem', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pecas_organization_id'), 'pecas', ['organization_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'category', name='uq_retention_org_category')
    )
    op.create_index(op.f('ix_retention_policies_organization_id'), 'retention_policies', ['organization_id'], unique=False)
    op.create_table('saved_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('recipient', sa.String(length=254), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_reports_next_run_at'), 'saved_reports', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_saved_reports_organization_id'), 'saved_reports', ['organization_id'], unique=False)
    op.create_table('user_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_invites_email'), 'user_invites', ['email'], unique=False)
    op.create_index(op.f('ix_user_invites_organization_id'), 'user_invites', ['organization_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('security_version', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_organization_id'), 'user_sessions', ['organization_id'], unique=False)
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('coletas_agendadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('numero_casa', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coletas_agendadas_cliente_id'), 'coletas_agendadas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_data_agendada'), 'coletas_agendadas', ['data_agendada'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_organization_id'), 'coletas_agendadas', ['organization_id'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_os_id'), 'coletas_agendadas', ['os_id'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_status'), 'coletas_agendadas', ['status'], unique=False)
    op.create_index(op.f('ix_coletas_agendadas_usuario_id'), 'coletas_agendadas', ['usuario_id'], unique=False)
    op.create_table('inventory_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_lot_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['pecas.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'part_id', 'code', name='uq_inventory_lot_part_code')
    )
    op.create_index(op.f('ix_inventory_lots_expires_at'), 'inventory_lots', ['expires_at'], unique=False)
    op.create_index(op.f('ix_inventory_lots_organization_id'), 'inventory_lots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_lots_part_id'), 'inventory_lots', ['part_id'], unique=False)
    op.create_table('laudos_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_uuid', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('emitido_em', sa.DateTime(), nullable=True),
    sa.Column('analisado_em', sa.DateTime(), nullable=True),
    sa.Column('tecnico_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_responsavel_nome', sa.String(length=120), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('laudo_origem_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('defeito_relatado', sa.Text(), nullable=True),
    sa.Column('inspecao_visual', sa.Text(), nullable=True),
    sa.Column('testes_realizados', sa.Text(), nullable=True),
    sa.Column('instrumentos_metodos', sa.Text(), nullable=True),
    sa.Column('medicoes', sa.Text(), nullable=True),
    sa.Column('diagnostico_tecnico', sa.Text(), nullable=True),
    sa.Column('causa_provavel', sa.Text(), nullable=True),
    sa.Column('servicos_realizados', sa.Text(), nullable=True),
    sa.Column('pecas_utilizadas', sa.Text(), nullable=True),
    sa.Column('conclusao_tecnica', sa.Text(), nullable=True),
    sa.Column('estado_final', sa.String(length=120), nullable=True),
    sa.Column('recomendacoes', sa.Text(), nullable=True),
    sa.Column('riscos_limitacoes', sa.Text(), nullable=True),
    sa.Column('garantia', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('empresa_snapshot', sa.JSON(), nullable=True),
    sa.Column('cliente_snapshot', sa.JSON(), nullable=True),
    sa.Column('equipamento_snapshot', sa.JSON(), nullable=True),
    sa.Column('tecnico_snapshot', sa.JSON(), nullable=True),
    sa.Column('template_snapshot', sa.JSON(), nullable=True),
    sa.Column('assinatura_tecnico_nome', sa.String(length=120), nullable=True),
    sa.Column('assinatura_tecnico_em', sa.DateTime(), nullable=True),
    sa.Column('assinatura_tecnico_metodo', sa.String(length=50), nullable=True),
    sa.Column('assinatura_cliente_nome', sa.String(length=120), nullable=True),
    sa.Column('assinatura_cliente_em', sa.DateTime(), nullable=True),
    sa.Column('assinatura_cliente_metodo', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(length=600), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('pdf_gerado_em', sa.DateTime(), nullable=True),
    sa.Column('pdf_template_version', sa.String(length=30), nullable=True),
    sa.Column('verification_token', sa.String(length=80), nullable=True),
    sa.Column('verificacao_publica', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['laudo_origem_id'], ['laudos_tecnicos.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['tecnico_responsavel_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['laudo_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'numero', name='uq_laudo_org_numero'),
    sa.UniqueConstraint('public_uuid'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index('ix_laudos_cliente_id', 'laudos_tecnicos', ['cliente_id'], unique=False)
    op.create_index('ix_laudos_emitido_em', 'laudos_tecnicos', ['emitido_em'], unique=False)
    op.create_index('ix_laudos_os_id', 'laudos_tecnicos', ['os_id'], unique=False)
    op.create_index('ix_laudos_public_uuid', 'laudos_tecnicos', ['public_uuid'], unique=False)
    op.create_index('ix_laudos_status', 'laudos_tecnicos', ['status'], unique=False)
    op.create_index('ix_laudos_verification_token', 'laudos_tecnicos', ['verification_token'], unique=False)
    op.create_table('order_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('captured_by_id', sa.Integer(), nullable=False),
    sa.Column('signer_name', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['captured_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_order_signatures_order_id'), 'order_signatures', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_signatures_organization_id'), 'order_signatures', ['organization_id'], unique=False)
    op.create_table('os_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_historico_organization_id'), 'os_historico', ['organization_id'], unique=False)
    op.create_table('os_pecas',
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('os_id', 'peca_id')
    )
    op.create_table('portal_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('revogado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_portal_token_os_purpose', 'portal_tokens', ['os_id', 'purpose', 'revogado_em'], unique=False)
    op.create_index(op.f('ix_portal_tokens_organization_id'), 'portal_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_portal_tokens_os_id'), 'portal_tokens', ['os_id'], unique=False)
    op.create_table('stock_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['pecas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_reservation_active', 'stock_reservations', ['part_id', 'status'], unique=False)
    op.create_index(op.f('ix_stock_reservations_order_id'), 'stock_reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_organization_id'), 'stock_reservations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_part_id'), 'stock_reservations', ['part_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_status'), 'stock_reservations', ['status'], unique=False)
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parcela_numero', sa.Integer(), nullable=False),
    sa.Column('parcela_total', sa.Integer(), nullable=False),
    sa.Column('recorrencia', sa.String(length=20), nullable=True),
    sa.Column('conciliado_em', sa.DateTime(), nullable=True),
    sa.Column('conciliado_por_id', sa.Integer(), nullable=True),
    sa.Column('conciliacao_ref', sa.String(length=120), nullable=True),
    sa.Column('comissao_usuario_id', sa.Integer(), nullable=True),
    sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comissao_valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_gateway', sa.String(length=40), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('payment_provider_id', sa.String(length=160), nullable=True),
    sa.Column('payment_status', sa.String(length=40), nullable=True),
    sa.Column('payment_url', sa.String(length=600), nullable=True),
    sa.Column('payment_link', sa.String(length=600), nullable=True),
    sa.Column('payment_barcode', sa.String(length=300), nullable=True),
    sa.Column('payment_payload', sa.Text(), nullable=True),
    sa.Column('payment_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['conciliado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_organization_id'), 'transacoes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_transacoes_parent_id'), 'transacoes', ['parent_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['pecas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_lot_id'), 'inventory_movements', ['lot_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_order_id'), 'inventory_movements', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_organization_id'), 'inventory_movements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_part_id'), 'inventory_movements', ['part_id'], unique=False)
    op.create_table('laudo_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('laudo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dados', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudos_tecnicos.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_laudo_eventos_laudo', 'laudo_eventos', ['laudo_id', 'criado_em'], unique=False)
    op.create_index(op.f('ix_laudo_eventos_organization_id'), 'laudo_eventos', ['organization_id'], unique=False)
    op.create_table('laudo_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('laudo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('legenda', sa.String(length=255), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=600), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=600), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudos_tecnicos.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_laudo_fotos_laudo_tipo', 'laudo_fotos', ['laudo_id', 'tipo'], unique=False)
    op.create_index(op.f('ix_laudo_fotos_organization_id'), 'laudo_fotos', ['organization_id'], unique=False)
    op.create_table('os_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('coleta_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coleta_id'], ['coletas_agendadas.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_fotos_coleta_id'), 'os_fotos', ['coleta_id'], unique=False)
    op.create_index(op.f('ix_os_fotos_organization_id'), 'os_fotos', ['organization_id'], unique=False)
    op.create_index(op.f('ix_os_fotos_os_id'), 'os_fotos', ['os_id'], unique=False)
    op.create_index(op.f('ix_os_fotos_usuario_id'), 'os_fotos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    for table_name in (
        'os_fotos',
        'laudo_fotos',
        'laudo_eventos',
        'inventory_movements',
        'transacoes',
        'stock_reservations',
        'portal_tokens',
        'os_pecas',
        'os_historico',
        'order_signatures',
        'laudos_tecnicos',
        'inventory_lots',
        'coletas_agendadas',
        'user_sessions',
        'user_invites',
        'saved_reports',
        'retention_policies',
        'pecas',
        'password_reset_tokens',
        'ordens_servico',
        'laudo_templates',
        'eventos_log',
        'data_subject_requests',
        'consent_records',
        'usuarios',
        'service_checklist_templates',
        'organization_subscriptions',
        'notifications',
        'message_templates',
        'fornecedores',
        'defeitos_padrao',
        'configuracoes',
        'clientes',
        'billing_events',
        'plans',
        'organizations',
        'operational_heartbeats',
        'operational_alerts',
        'login_attempts',
        'laudo_counters',
        'api_rate_limits',
    ):
        op.drop_table(table_name)
